version: '3.5'


x-defaults: &defaults
  logging:
    driver: json-file
    options:
      max-size: 2m
      max-file: 5
# environment:
#   GRPC_VERBOSITY: debug
#   GRPC_TRACE: tcp,http,secure_endpoint,transport_security


services:

    # AMS Control
    ctrl:
        <<: *defaults
        image: iams:local
        command: tasks.cfssl:8888 -d
        environment:
            IAMS_NETWORK: iams_ams
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
            placement:
                constraints: [node.role == manager]
        networks:
            - cfssl
            - envoy
            - iams

    # Simulation
    sim:
        <<: *defaults
        image: iams:local
        command: --simulation tasks.cfssl:8888 -d
        environment:
            IAMS_NETWORK: iams_test
        ports:
            - "5115:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
            placement:
                constraints: [node.role == manager]
        networks:
            - cfssl
            - test

    cfssl:
        <<: *defaults
        image: glomium/cfssl:latest
        ports:
            - "8888:8888"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
        secrets:
            - ca.crt
            - ca.key
        networks:
            - cfssl

    arangodb:
        <<: *defaults
        image: arangodb:3.6.1
        ports:
            - "8529:8529"
        volumes:
            - arango-apps:/var/lib/arangodb3-apps
            - arango-data:/var/lib/arangodb3
        environment:
            ARANGO_ROOT_PASSWORD: "secret_password"
        deploy:
            mode: replicated
            replicas: 1
        networks:
            - arango

networks:
    arango:
    cfssl:
    iams:
    envoy:
    test:

volumes:
    arango-apps:
    arango-data:

secrets:
    ca.key:
        file: ./secrets/ca.key
    ca.crt:
        file: ./secrets/ca.crt
