version: '3.7'


services:

    cfssl:
        image: glomium/cfssl:latest
        ports:
            - "8888:8888"
        secrets:
            - ca.crt
            - ca.key

    arangodb:
        image: arangodb:3.6.5
        environment:
            ARANGO_ROOT_PASSWORD_FILE: /run/secrets/arango
        ports:
            - "8529:8529"
        secrets:
            - arango

secrets:
    arango:
        file: ./secrets/arango
    ca.key:
        file: ./secrets/ca.key
    ca.crt:
        file: ./secrets/ca.crt
