version: '3.7'

services:
    sut:
        image: iams_test:local
        build:
            context: .
            dockerfile: Dockerfile
            args:
                UBUNTU: rolling
            target: test
        depends_on:
            - arangodb
            - cfssl
        entrypoint: '/bin/sh run_tests.sh'
        environment:
            IAMS_ARANGO_HOSTS: http://arangodb:8529
        networks:
            - arango
            - cfssl
        secrets:
            - arango
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    cfssl:
        image: glomium/cfssl:latest
        secrets:
            - ca.crt
            - ca.key
        networks:
            - cfssl

    arangodb:
        image: arangodb:3.6.1
        environment:
            ARANGO_ROOT_PASSWORD_FILE: /run/secrets/arango
        secrets:
            - arango
        networks:
            - arango

    # build containers for examples

    market_sink:
        build:
            context: examples/market
            dockerfile: Dockerfile_sink
        entrypoint: sleep 86400
        depends_on:
            - sut
        image: iams_market_sink:local

    market_source:
        build:
            context: examples/market
            dockerfile: Dockerfile_source
        entrypoint: sleep 86400
        depends_on:
            - sut
        image: iams_market_source:local

    simulation_sink:
        build:
            context: examples/simulation
            dockerfile: Dockerfile_sink
        entrypoint: sleep 86400
        depends_on:
            - sut
        image: iams_simulation_sink:local

    simulation_source:
        build:
            context: examples/simulation
            dockerfile: Dockerfile_source
        entrypoint: sleep 86400
        depends_on:
            - sut
        image: iams_simulation_source:local

    simulation_vehicle:
        build:
            context: examples/simulation
            dockerfile: Dockerfile_vehicle
        entrypoint: sleep 86400
        depends_on:
            - sut
        image: iams_simulation_vehicle:local


networks:
    arango:
    cfssl:


secrets:
    arango:
        file: ./secrets_test/arango
    ca.key:
        file: ./secrets_test/ca.key
    ca.crt:
        file: ./secrets_test/ca.crt
