version: '3.7'


services:

    cfssl:
        image: glomium/cfssl:latest
        ports:
            - "8888:8888"
        secrets:
            - ca.crt
            - ca.key

secrets:
    ca.key:
        file: ./secrets/ca.key
    ca.crt:
        file: ./secrets/ca.crt
