version: '3.5'


x-defaults: &defaults
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 5
    # environment:
    #   GRPC_VERBOSITY: debug
    #   GRPC_TRACE: tcp,http,secure_endpoint,transport_security


services:

    # AMS Control
    ctrl:
        <<: *defaults
        image: registry:5000/iams:latest
        command: tasks.cfssl:8888 -d
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
        networks:
            - cfssl
            - iams

    # Simulation
    sim:
        <<: *defaults
        image: registry:5000/iams:latest
        command: --simulation tasks.cfssl:8888 -d
        environment:
            IAMS_HOSTS: 10.6.30.69,192.168.42.65
        ports:
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
        networks:
            - cfssl
            - iams

    cfssl:
        <<: *defaults
        image: glomium/cfssl:latest
        ports:
            - "8888:8888"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
            placement:
                preferences:
                    - spread: node.labels.worker
        secrets:
            - ca.crt
            - ca.key
        networks:
            - cfssl

networks:
    cfssl:
    iams:

secrets:
    ca.key:
        file: ./secrets/ca.key
    ca.crt:
        file: ./secrets/ca.crt
