# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agv.proto',
  package='agv.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tagv.proto\x12\tagv.proto\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x04\x44\x61ta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x02\x32\xad\x01\n\x06Source\x12\x35\n\nnext_order\x12\x16.google.protobuf.Empty\x1a\x0f.agv.proto.Time\x12\x33\n\x08get_part\x12\x16.google.protobuf.Empty\x1a\x0f.agv.proto.Data\x12\x37\n\x0creserve_next\x12\x16.google.protobuf.Empty\x1a\x0f.agv.proto.Data2w\n\x04Sink\x12:\n\x0fget_coordinates\x12\x16.google.protobuf.Empty\x1a\x0f.agv.proto.Data\x12\x33\n\x08put_part\x12\x16.google.protobuf.Empty\x1a\x0f.agv.proto.Time2h\n\x07Vehicle\x12+\n\x07get_eta\x12\x0f.agv.proto.Data\x1a\x0f.agv.proto.Time\x12\x30\n\x05\x64rive\x12\x0f.agv.proto.Data\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='agv.proto.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='agv.proto.Data.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='agv.proto.Data.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='agv.proto.Data.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=95,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='agv.proto.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='agv.proto.Time.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Time'] = _TIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'agv_pb2'
  # @@protoc_insertion_point(class_scope:agv.proto.Data)
  })
_sym_db.RegisterMessage(Data)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'agv_pb2'
  # @@protoc_insertion_point(class_scope:agv.proto.Time)
  })
_sym_db.RegisterMessage(Time)



_SOURCE = _descriptor.ServiceDescriptor(
  name='Source',
  full_name='agv.proto.Source',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=120,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='next_order',
    full_name='agv.proto.Source.next_order',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TIME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_part',
    full_name='agv.proto.Source.get_part',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reserve_next',
    full_name='agv.proto.Source.reserve_next',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOURCE)

DESCRIPTOR.services_by_name['Source'] = _SOURCE


_SINK = _descriptor.ServiceDescriptor(
  name='Sink',
  full_name='agv.proto.Sink',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=295,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_coordinates',
    full_name='agv.proto.Sink.get_coordinates',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='put_part',
    full_name='agv.proto.Sink.put_part',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TIME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SINK)

DESCRIPTOR.services_by_name['Sink'] = _SINK


_VEHICLE = _descriptor.ServiceDescriptor(
  name='Vehicle',
  full_name='agv.proto.Vehicle',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=416,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_eta',
    full_name='agv.proto.Vehicle.get_eta',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_TIME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='drive',
    full_name='agv.proto.Vehicle.drive',
    index=1,
    containing_service=None,
    input_type=_DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VEHICLE)

DESCRIPTOR.services_by_name['Vehicle'] = _VEHICLE

# @@protoc_insertion_point(module_scope)
