# The image requires to run the build of iams on your setup
# Change FROM to the public image to build from dockerhub
# FROM glomium/industrial-ams:rolling
FROM iams:local

LABEL iams.services.agent=true

COPY simulation_pb2_grpc.py simulation_pb2.py source.py ./

ENTRYPOINT ["/usr/bin/python3", "source.py"]
