# The image requires to run the build of iams on your setup
# Change FROM to the public image to build from dockerhub
# FROM glomium/industrial-ams:rolling
FROM iams-test:local

COPY entrypoint.sh /
COPY example.proto machine1.py ./

RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. example.proto

LABEL iams.services.agent=true
LABEL iams.plugins.sentry=true
ENTRYPOINT ["/entrypoint.sh", "machine1.py"]
